version: '2'
services:
    binance_mdrecorder:
        build:
            context: .
            dockerfile: ./docker/binance_mdrecorder/Dockerfile
        container_name: "binance_mdrecorder"
        volumes:
            - /mnt/raid/data/behemoth:/behemoth
        depends_on:
            - scheduler
    coinbase_mdrecorder:
        build:
            context: .
            dockerfile: ./docker/coinbase_mdrecorder/Dockerfile
        container_name: "coinbase_mdrecorder"
        volumes:
            - /mnt/raid/data/behemoth:/behemoth
        depends_on:
            - scheduler
    scheduler:
        build:
            context: .
            dockerfile: ./docker/scheduler/Dockerfile
        container_name: "scheduler"
        volumes:
            - /mnt/raid/data/behemoth:/behemoth
