version: '2'
services:
    serenity_mdrecorder:
        build: .
        container_name: "serenity_mdrecorder"
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        volumes:
          - /mnt/raid/data/behemoth/arctic:/data/db
        ports:
            - 27017:27017
        command: mongod